import chai from "chai"

// Boolean category modules
import eq from "../src/eq.js"
import isArgument from "../src/isArguments.js"
import isArrayLike from "../src/isArrayLike.js"
import isArrayLikeObject from "../src/isArrayLikeObject.js"
import isBoolean from "../src/isBoolean.js"
import isBuffer from "../src/isBuffer.js"
import isDate from "../src/isDate.js"
import isEmpty from "../src/isEmpty.js"
import isLength from "../src/isLength.js"
import isObject from "../src/isObject.js"
import isObjectLike from "../src/isObjectLike.js"
import isSymbol from "../src/isSymbol.js"
import isTypedArray from "../src/isTypedArray.js"
